"""pedidos checkout y precios

Revision ID: 06c8023e5bca
Revises: e8e0d0c7e53b
Create Date: 2026-09-07 13:00:27.183061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c8023e5bca'
down_revision: Union[str, Sequence[str], None] = 'e8e0d0c7e53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items_pedido', 'pedido_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('items_pedido', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('items_pedido', 'cantidad',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('items_pedido', 'precio_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.add_column('pedidos', sa.Column('creado_en', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('pedidos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pedidos', 'total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False)
    op.alter_column('pedidos', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedidos', 'estado',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pedidos', 'total',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('pedidos', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('pedidos', 'creado_en')
    op.alter_column('items_pedido', 'precio_unitario',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('items_pedido', 'cantidad',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items_pedido', 'producto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items_pedido', 'pedido_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
