"""usuarios con auth

Revision ID: e8e0d0c7e53b
Revises: 69a8281f78b6
Create Date: 2026-09-07 08:38:43.319116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e0d0c7e53b'
down_revision: Union[str, Sequence[str], None] = '69a8281f78b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('hashed_password', sa.String(), nullable=False))
    op.add_column('usuarios', sa.Column('acepto_tratamiento', sa.Boolean(), nullable=False))
    op.add_column('usuarios', sa.Column('fecha_consentimiento', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('usuarios', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('usuarios', 'rol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'nombre',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('usuarios', 'fecha_consentimiento')
    op.drop_column('usuarios', 'acepto_tratamiento')
    op.drop_column('usuarios', 'hashed_password')
    # ### end Alembic commands ###
